services:
  frontend:
    build:
      context: ./react-frontend 
    ports:
      - "14381:14381" 
    volumes:
      - ./react-frontend:/app 
    depends_on:   
      - backend
  backend:
    build:
      context: ./flask-backend
    ports:
      - "5000:5000" 
    volumes:
      - ./flask-backend:/app
      - dbdata:/app/db

volumes:
  dbdata: